[book]
authors = ["zqc17"]
language = "zh-CN"
multilingual = false
src = "md"
title = "陶哲轩实分析 - Lean语言描述"
description = "note for learning lean"

[build]
create-missing = false
build-dir = "book"

[output.html]
no-section-label = false
git-repository-url = "https://github.com/Seasawher/lean-book"
edit-url-template = "https://raw.githubusercontent.com/Seasawher/lean-book/main/{path}"
site-url = "https://zqc17.github.io/analysis-lean/"
additional-js = [
  # Add "Run on Lean4 Playground" button to each code block
  "assets/blockPlay.js",

  # Add "Run on Lean4 Playground" button to each page
  "assets/filePlay.js",

  # Improve search functionality
  "assets/fzf.umd.js",
  "assets/elasticlunr.js"
]
